# Generated by Django 4.1.2 on 2022-10-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='crate_at',
            new_name='create_at',
        ),
    ]
