# Generated by Django 4.1.2 on 2022-10-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0003_track_cover_track_ptivate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='ptivate',
            new_name='private',
        ),
    ]
